rpc/item: fix kernel module build on Ubuntu-18.04
  CC [M]  /home/ant/motr/rpc/item.o
/home/ant/motr/rpc/item.c: In function ‘m0_rpc_item_module_init’:
/home/ant/motr/rpc/item.c:133:1: error: the frame size of 1568 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Problem: the big m0_xcode_ctx local vars are used several times.

Solution: restructure the usage of local vars and use several
int vars to store different xcode_lengths for different items
instead of several m0_xcode_ctx vars.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>