CORTX-31292: fix m0tr.ko build regression
The regression was introduced at commit 446fe0372:

    motr/io_req.c:1736:21: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘m0_bcount_t’ {aka ‘long long unsigned int’} [-Werror=format=]
       M0_LOG(M0_NOTICE, "user data written with degraded redundancy: "
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Solution: use PRIu64 format for printing m0_bcount_t.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>