fdmi/module.c: fix compilation error with gcc-8.3
  fdmi/module.c:32:31: error: ‘levels_fdmi’ defined but not used [-Werror=unused-const-variable=]
   static const struct m0_modlev levels_fdmi[] = {
                                 ^~~~~~~~~~~
  cc1: all warnings being treated as errors

Solution: comment out unused code.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>