Fix issues with clang compiler (#557)
* lib/trace: avoid explicit register variable for clang

Clang doesn't support explicit register variable which is a gcc
extension. Address of a variable on stack can be used an approximation
of the stack pointer.

* rpc/ut: avoid nested functions

C standard doesn't allow nested functions and clang doesn't support
them. Move such functions to the file scope. This change doesn't affect
functionality and makes the code be more standard compliant.

* ioservice/ut/bulkio_ut: rename global variable i

'i' is not a good name for a global variable, especially when local
variables with the same name shadow it. This naming is error prone.
Rename it to 'nb_nr' to represent its nature.

* fd/ut: suppress uninitialised warning

Clang complains that failure_level can be used uninitialised. Initialise
this variable to suppress the warning.

* net/test: cast UINT64_MAX to double explicitly

This change fixes the following clang warning:
net/test/user_space/stats_u.c:40:41: error: implicit conversion from
'unsigned long' to 'double' changes value from 18446744073709551615 to
18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
        return v128->u_lo * 1. + v128->u_hi * (UINT64_MAX + 1.);
                                               ^~~~~~~~~~ ~
/usr/include/stdint.h:130:23: note: expanded from macro 'UINT64_MAX'
 # define UINT64_MAX             (__UINT64_C(18446744073709551615))
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:107:25: note: expanded from macro '__UINT64_C'
 #  define __UINT64_C(c) c ## UL
                         ^~~~~~~
<scratch space>:60:1: note: expanded from here
18446744073709551615UL
^~~~~~~~~~~~~~~~~~~~~~

* net/test/console: fix format for bool argument

LOGD() is provided with format "%c" for a boolean variable. "%d" is more
suitable here.

* Mark unused static functions with M0_UNUSED

Clang complains about unused static functions. Also it can be useful for
tracking unused functions with a simple grep.

Signed-off-by: Dmitry Podgorny <pasis.ua@gmail.com>