layout/composite.c: fix compilation error with gcc-8.3
  layout/composite.c:223:35: error: ‘composite_ops’ defined but not used [-Werror=unused-const-variable=]
   static const struct m0_layout_ops composite_ops = {
                                     ^~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Solution: comment out unused code.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>