mdservice/md_fops: fix kernel module build on Ubuntu-18.04
  CC [M]  /home/ant/motr/mdservice/md_fops.o
/home/ant/motr/mdservice/md_fops.c: In function ‘m0_mdservice_fopts_init’:
/home/ant/motr/mdservice/md_fops.c:255:1: error: the frame size of 1088 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
/home/ant/motr/mdservice/md_fops.c: In function ‘m0_mdservice_rep_fopts_init’:
/home/ant/motr/mdservice/md_fops.c:335:1: error: the frame size of 1088 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Solution: introduce and use M0_FOP_TYPE_INIT2() and
M0_FOP_TYPE_INIT2_DECL macro which re-use the same variable
on each M0_FOP_TYPE_INIT2() call instead of defining
the new one on the stack each time it's called.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>