console: fix compilation error on CentOS-8
The compilation of byte_set() function by gcc-8.3 fails:

  console/console_it.c:85:3: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
     strncpy(data, tmp_value, strlen(tmp_value));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Solution: use simple assignment with typecast *(char*) instead of
strncpy(). For the byte type it's more than enough.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>