dtm/remote.c: fix compilation error with gcc-8.3
  dtm/remote.c:262:37: error: ‘rem_rpc_item_redo_ops’ defined but not used [-Werror=unused-const-variable=]
   static const struct m0_rpc_item_ops rem_rpc_item_redo_ops = {
                                       ^~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

  dtm/remote.c:248:13: error: ‘rem_rpc_redo_replied’ defined but not used [-Werror=unused-function]
   static void rem_rpc_redo_replied(struct m0_rpc_item *item)
               ^~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Solution: comment out unused items.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>