stob/module.c: fix compilation error with gcc-8.3
  stob/module.c:29:31: error: ‘levels_stob’ defined but not used [-Werror=unused-const-variable=]
   static const struct m0_modlev levels_stob[] = {
                                 ^~~~~~~~~~~
  cc1: all warnings being treated as errors

Solution: comment out unused code.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>